<?php

namespace MyModule\View\Helper\MyMixin;

use Laminas\View\Helper\AbstractHelper;

class MyHelper extends AbstractHelper
{
    public function getExampleText(): string
    {
        return 'This text is generated by ' . __CLASS__;
    }
}
